# Generated by Django 4.2.7 on 2023-11-30 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0003_alter_sellernotes_note_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downloads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_seller_has_allowed_to_download', models.BooleanField(default=False)),
                ('attachment_path', models.CharField(blank=True, max_length=500, null=True)),
                ('is_attachment_downloaded', models.BooleanField(default=False)),
                ('attachment_downloaded_date', models.DateTimeField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('purchased_price', models.IntegerField(default=0)),
                ('note_title', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_downloads', to=settings.AUTH_USER_MODEL)),
                ('downloader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='downloader_downloads', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_downloads', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='notes.sellernotes')),
                ('note_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='super_admin.notecategory')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='seller_downloads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
