# Generated by Django 4.2.7 on 2023-11-30 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_downloads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloads',
            name='note_category',
        ),
        migrations.RemoveField(
            model_name='downloads',
            name='note_title',
        ),
    ]
