# Generated by Django 4.2.7 on 2023-11-30 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0001_initial'),
        ('notes', '0007_sellernotesreportedissues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellernotes',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_notes', to='super_admin.notecategory'),
        ),
        migrations.AlterField(
            model_name='sellernotes',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='country_notes', to='super_admin.country'),
        ),
        migrations.AlterField(
            model_name='sellernotes',
            name='note_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='note_notes', to='super_admin.notetype'),
        ),
        migrations.AlterField(
            model_name='sellernotes',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'In Review')], default=1),
        ),
    ]
