# Generated by Django 4.2.7 on 2023-11-30 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0001_initial'),
        ('notes', '0008_alter_sellernotes_category_alter_sellernotes_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellernotes',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='country_notes', to='super_admin.country'),
        ),
        migrations.AlterField(
            model_name='sellernotes',
            name='note_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='note_notes', to='super_admin.notetype'),
        ),
    ]
