# Generated by Django 4.2.7 on 2023-12-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_alter_sellernotes_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellernotes',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Submitted'), (3, 'In Review'), (4, 'Approved'), (5, 'Rejected')], default=1),
        ),
    ]
