# Generated by Django 4.2.7 on 2023-12-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_alter_sellernotes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellernotes',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Draft'), (2, 'Submitted'), (3, 'In Review'), (4, 'Approved'), (5, 'Rejected'), (6, 'Removed')], default=1),
        ),
    ]
