# Generated by Django 4.2.7 on 2023-12-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_remove_downloads_attachment_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellernotesreportedissues',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
