# Generated by Django 4.2.7 on 2023-12-04 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0001_initial'),
        ('authenticate', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='zipCode',
            new_name='zip_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='country_user', to='super_admin.country'),
        ),
    ]
