# Generated by Django 4.2.7 on 2023-12-06 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_admin', '0001_initial'),
        ('authenticate', '0003_rename_zipcode_user_zip_code_alter_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='country_user', to='super_admin.country'),
        ),
    ]
